---
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  namespace: podinfo-mesh
  name: allow-gateway
spec:
  targetRef:
    kind: MeshService
    name: podinfo_podinfo-mesh_svc_9898
  from:
    - targetRef:
        kind: MeshSubset
        tags:
          k8s.kuma.io/namespace: kong
          k8s.kuma.io/service-name: kong-kong-admin
      default:
        action: Allow
---
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  namespace: podinfo-mesh
  name: allow-podinfo
spec:
  targetRef:
    kind: MeshService
    name: podinfo_podinfo-mesh_svc_9898
  from:
    - targetRef:
        kind: MeshService
        name: tomcat-metallb_tomcat-metallb-mesh_svc_8080
      default:
        action: Allow
---
