apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-apisix-dev
  namespace: ingress-apisix
spec:
  commonName: admin.apisix.dev
  dnsNames:
    - admin.apisix.dev
  issuerRef:
    name: vault-issuer
    kind: Issuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  secretName: admin-apisix-dev