apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
  namespace: prometheus
spec:
  commonName: grafana
  dnsNames:
    - grafana
  issuerRef:
    name: vault-issuer
    kind: Issuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    rotationPolicy: Always
    size: 4096
  secretName: grafana-tls