---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-ldap
  namespace: prometheus
spec:
  secretStoreRef:
    name: okd4-grafana
    kind: SecretStore
  target:
    name: grafana-ldap
  data:
  - secretKey: ldap-toml
    remoteRef:
      key: kv/okd4/production/grafana
      property: config-ldap