---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: prometheus
spec:
  secretStoreRef:
    name: okd4-grafana
    kind: SecretStore
  target:
    name: grafana
  data:
  - secretKey: admin-user
    remoteRef:
      key: kv/okd4/production/grafana
      property: admin-user
  - secretKey: admin-password
    remoteRef:
      key: kv/okd4/production/grafana
      property: admin-password