apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 172.18.0.100-172.18.0.255
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-apisix
  namespace: metallb-system
spec:
  addresses:
  - 10.11.1.50-10.11.1.99
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system

