---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: node-custom-setup
  name: node-custom-setup
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: node-custom-setup
  template:
    metadata:
      labels:
        k8s-app: node-custom-setup
    spec:
      containers:
      - image: k8s.gcr.io/pause:3.5
        imagePullPolicy: IfNotPresent
        name: wait
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      initContainers:
      - args:
        - --mount=/proc/1/ns/mnt
        - --
        - sh
        - -c
        - $(UPDATE_CA)
        command:
        - nsenter
        env:
        - name: PFSENSE_LAB_ROOT_CA
          valueFrom:
            configMapKeyRef:
              key: pfsense_lab_root_ca.crt
              name: trusted-ca
        - name: PFSENSE_OKD_INTERMEDIATE_CA
          valueFrom:
            configMapKeyRef:
              key: pfsense_okd_intermediate_ca.crt
              name: trusted-ca
        - name: UPDATE_CA
          valueFrom:
            configMapKeyRef:
              key: update-ca-cert.sh
              name: deploy-ca-crt-script
        image: registry.fedoraproject.org/fedora:37
        imagePullPolicy: Always
        name: init-node
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
data:
  update-ca-cert.sh: |
    # Fedora
    echo "$PFSENSE_LAB_ROOT_CA" | tee /etc/pki/ca-trust/source/anchors/pfsense_lab_root_ca.crt
    echo "$PFSENSE_OKD_INTERMEDIATE_CA" | tee /etc/pki/ca-trust/source/anchors/pfsense_okd_intermediate_ca.crt
    update-ca-trust force-enable
    update-ca-trust extract
    systemctl restart crio
    systemctl status crio
kind: ConfigMap
metadata:
  name: deploy-ca-crt-script
  namespace: kube-system
---
apiVersion: v1
data:
  pfsense_okd_intermediate_ca.crt: |
    # Owner: O=pfsense.lab, L=PAT, ST=Quebec, C=CA, CN=pfSense OKD Intermediate CA
    -----BEGIN CERTIFICATE-----
    MIIEDjCCAvagAwIBAgIBBDANBgkqhkiG9w0BAQsFADBgMRwwGgYDVQQDExNwZlNl
    bnNlIExhYiBSb290IENBMQswCQYDVQQGEwJDQTEPMA0GA1UECBMGUXVlYmVjMQww
    CgYDVQQHEwNQQVQxFDASBgNVBAoTC3Bmc2Vuc2UubGFiMCAXDTIwMTExNTA2MDM1
    NloYDzIxMjAxMDIyMDYwMzU2WjBnMSMwIQYDVQQDExpwZlNlbnNlIE9LRCBJbnRl
    bWVkaWF0ZSBDQTELMAkGA1UEBhMCQ0ExDzANBgNVBAgTBlF1ZWJlYzEMMAoGA1UE
    BxMDUEFUMRQwEgYDVQQKEwtwZnNlbnNlLmxhYjCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBAOtZK11Y6ZcnBToFzxrQUC1iYAxRBp2KY5dQRa6L+bxmzL0B
    yCIwR3CfzFXBN3a1/Xf5z0yBachw6hAy2vd1qG+K1jdwwYTCaF6R3Eh+2qPxWjgU
    ugRfy5xu8IfYLVkF0UCPCSUoiEyammrzvFVHH0GCzCHCruO6xdHrMXfMnxZQSQDh
    yHQcWNlRIgac7hY0A0lWIi8iaLeJ61ohaO0KBttTaUqsDFUK+F+LYM65Gu2WfSCb
    arfkhVpd899gxOkD4+4venYhHrMGTZZCXQk695tEwtdu9OSPbq21h4L1RbIXrOiy
    c0vbqw90PCPBNsn20AQbxhiNHeIBtdTprjPfF/UCAwEAAaOByTCBxjAdBgNVHQ4E
    FgQUSV0PbLpu9x2u2ky8ZiNHs+m9WZwwgYkGA1UdIwSBgTB/gBRRSMwwHMIk3Xzh
    LmO/SEl3BPFHeKFkpGIwYDEcMBoGA1UEAxMTcGZTZW5zZSBMYWIgUm9vdCBDQTEL
    MAkGA1UEBhMCQ0ExDzANBgNVBAgTBlF1ZWJlYzEMMAoGA1UEBxMDUEFUMRQwEgYD
    VQQKEwtwZnNlbnNlLmxhYoIBADAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIBBjAN
    BgkqhkiG9w0BAQsFAAOCAQEAwiEeYnLvpHWZQnN+siot6Y4tNnqlYaOdQnjsGnad
    M7n+DCfqHybLd97D4wCOOcRIwAjNOgB6ybZhOgW+ENnnQArNt7zZw2i/57eiWTM4
    NqSRAR6KsyMwYL0AZMR94WSeO0cgvZxdQhrKWgMLbLdNWV23iKjRqgrNGMiOS1Ke
    jyLzAlXAz4mplkksYc/JHR1ORcPyLCSsnKyvj331HCMzUQmkZf14QAi+gQpQP3if
    vNtZitRzSokaxQ6123g4K5laiDfyk58YwH5DJ5UR2mvYaleg/Aa0B5flesvqH77E
    cNVyd4MWFANlsBPwCUjGGIw8CAbyuvos8Z01L6rLMLALNw==
    -----END CERTIFICATE-----
  pfsense_lab_root_ca.crt: |
    # Owner: O=pfsense.lab, L=PAT, ST=Quebec, C=CA, CN=pfSense Lab Root CA
    -----BEGIN CERTIFICATE-----
    MIIEBTCCAu2gAwIBAgIBADANBgkqhkiG9w0BAQsFADBgMRwwGgYDVQQDExNwZlNl
    bnNlIExhYiBSb290IENBMQswCQYDVQQGEwJDQTEPMA0GA1UECBMGUXVlYmVjMQww
    CgYDVQQHEwNQQVQxFDASBgNVBAoTC3Bmc2Vuc2UubGFiMB4XDTIwMDcwODE3Mzcw
    OVoXDTMwMDcwNjE3MzcwOVowYDEcMBoGA1UEAxMTcGZTZW5zZSBMYWIgUm9vdCBD
    QTELMAkGA1UEBhMCQ0ExDzANBgNVBAgTBlF1ZWJlYzEMMAoGA1UEBxMDUEFUMRQw
    EgYDVQQKEwtwZnNlbnNlLmxhYjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
    ggEBAOVwDa+ygzKSGX0htZ897QJzF4BdMTL4/H1cCbVbGUxdgWOfm4Bm8jSaFiCO
    0Fx4HzmJ5ObqUQh6Tb62IrMBi4IbJZI8/3JVREZx4f4K+T1E2A8VdtP7Kvlvtodp
    Hy139fSK0Eut7uLMEMC9HaowRXTvuB6V2tZQGDL7vse1iKMSO/BfqQ44pB4BpJNH
    O53Rv9uZIE7b1T9lqNU0O6bEn1hdd96CCFsuAxnFbd4ITrmgXE2jsf2UX/Bykuph
    hQvgOcNEU0rB4LMVAVXfcb+BicHnMparlB0USDWXZNyDscJsP3b0pO75OlY6a3LC
    YSnKhsnIrEXq1365Oc9j9TdJziUCAwEAAaOByTCBxjAdBgNVHQ4EFgQUUUjMMBzC
    JN184S5jv0hJdwTxR3gwgYkGA1UdIwSBgTB/gBRRSMwwHMIk3XzhLmO/SEl3BPFH
    eKFkpGIwYDEcMBoGA1UEAxMTcGZTZW5zZSBMYWIgUm9vdCBDQTELMAkGA1UEBhMC
    Q0ExDzANBgNVBAgTBlF1ZWJlYzEMMAoGA1UEBxMDUEFUMRQwEgYDVQQKEwtwZnNl
    bnNlLmxhYoIBADAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIBBjANBgkqhkiG9w0B
    AQsFAAOCAQEAYienYZE3reVPZ8n+pwvFmJl1JYeo9dzUeEpXU/mZZBdyHsYusQeQ
    /mzZM9au6kjCYS6qr6sCNGx/lSHann7lP6KMCDyL86+KEoLOWOGB7CwOK7HSWxO+
    hvmOsigK+UoNfmNln8eECU5KfPCRQxkWITXVn9OOVCvDl6zbSIwlM2FbseXAd+W2
    1ol3KtVrk2xRVa4g6gQnjRKaTEFl5QMvC9NEouhmtZRf/bfW0zpArfombFT9PpeT
    /moarJnO/ARGcpXkl7YZgmgdZ+mfIkupiinwWjLj/9DwYl8wMoLN0gmPDx6b613F
    0FBOAVL6iXotIYqVRwbUg5OjjqYibNOLTg==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: trusted-ca
  namespace: kube-system
