---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: welcome-app-prod
  namespace: welcome-app-prod
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: welcome-app-prod
  path: ./overlays/prod
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: welcome-app-prod
  namespace: welcome-app-prod
spec:
  interval: 1m0s
  ref:
    branch: develop
  secretRef:
    name: external-secret-welcome-app-prod-repository
  url: https://gitlab.lab.okd.local/gitops-tekton-welcome/welcome-deploy.git
