---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kong-oidc-plugin-config
  namespace: kong
spec:
  secretStoreRef:
    name: okd4-kong
    kind: SecretStore
  target:
    name: kong-oidc-plugin-config
    template:
      data:
        client_id: kong
        client_secret: "{{ .client_secret }}"
  data:
  - secretKey: client_secret 
    remoteRef:
      key: kv/okd4/production/keycloak/openid-clients/kong
      property: kong.client_secret
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: okd4-kong
  namespace: kong
spec:
  provider:
    vault:
      server: ${vault_address}
      path: ${vault_kv_engine_secret_mount_path}
      auth:
        kubernetes:
          mountPath: ${vault_auth_kubernetes_mount_path}
          role: kong
