---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-webhook
  namespace: welcome-app-pipeline
spec:
  secretStoreRef:
    name: gitops-tekton-welcome-pipeline
    kind: SecretStore
  target:
    name: external-secret-gitlab-webhook
    template:
      type: Opaque
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: "1"
      data:
        secretToken: "{{ .secretToken }}"
  data:
  - secretKey: secretToken 
    remoteRef:
      key: kv/gitops/tekton-welcome-pipeline/gitlab-webhook
      property: secretToken
