apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-ssh-key
  namespace: welcome-app-pipeline
spec:
  secretStoreRef:
    name: gitops-tekton-welcome-pipeline
    kind: SecretStore
  target:
    name: external-secret-gitlab-ssh-key
    template:
      type: kubernetes.io/ssh-auth
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: "1"
          tekton.dev/git-0: gitlab.lab.okd.local
      data:
        ssh-privatekey: "{{ .ssh_privatekey }}"
  data:
  - secretKey: ssh_privatekey
    remoteRef:
      key: kv/gitops/tekton-welcome-pipeline/gitlab-ssh
      property: ssh-privatekey 
