apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: welcome-app-pipeline-repository
  namespace: external-secrets
spec:
  secretStoreRef:
    name: welcome-app-pipeline-repository
    kind: SecretStore
  target:
    name: external-secret-welcome-app-pipeline-repository
  data:
  - secretKey: identity
    remoteRef:
      key: kv/okd4/okd4-cli
      property: flux_production_identity
  - secretKey: identity.pub 
    remoteRef:
      key: kv/okd4/okd4-cli
      property: flux_production_identity_pub
  - secretKey: known_hosts 
    remoteRef:
      key: kv/okd4/okd4-cli
      property: known_hosts
