apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus3-image-registry-opaque
  namespace: external-secrets
spec:
  secretStoreRef:
    name: gitops-tekton-welcome-pipeline
    kind: SecretStore
  target:
    name: external-secret-nexus3-image-registry-opaque
  data:
  - secretKey: username
    remoteRef:
      key: kv/gitops/tekton-welcome-pipeline/nexus3-image-registry
      property: username
  - secretKey: password
    remoteRef:
      key: kv/gitops/tekton-welcome-pipeline/nexus3-image-registry
      property: password
