---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gitops-tekton-welcome-pipeline
  namespace: external-secrets
spec:
  provider:
    vault:
      server: https://okd4-vault-1.lab.okd.local:8200
      path: kv/gitops/tekton-welcome-pipeline
      auth:
        kubernetes:
          mountPath: "kubernetes-okd4"
          role: "external-secrets-gitops"
