---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: welcome-app-pipeline-repository
  namespace: external-secrets
spec:
  provider:
    vault:
      server: https://okd4-vault-1.lab.okd.local:8200
      path: kv/okd4
      auth:
        kubernetes:
          mountPath: "kubernetes-okd4"
          role: "external-secrets-okd4"
