apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 24h
  type: oci
  url: oci://registry.lab.okd.local/helm-charts/prometheus-community.github.io/helm-charts
