---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: regcred
  namespace: flux-system
spec:
  provider:
    vault:
      server: ${vault_address}
      path: ${vault_kv_engine_secret_mount_path}
      auth:
        kubernetes:
          mountPath: ${vault_auth_kubernetes_mount_path}
          role: flux-system
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: regcred
  namespace: flux-system
spec:
  secretStoreRef:
    name: regcred
    kind: SecretStore
  target:
    name: regcred
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"${anon_image_registry_host}":{"username":"{{ .username }}","password":"{{ .password }}", "auth":"{{ printf "%s:%s" .user .password | b64enc }}"}}}'
  data:
    - secretKey: username 
      remoteRef:
        key: kv/okd4/production/image-registry
        property: username
    - secretKey: password
      remoteRef:
        key: kv/okd4/production/image-registry
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: regcred-ca
  namespace: flux-system
spec:
  secretStoreRef:
    name: regcred
    kind: SecretStore
  target:
    name: regcred-ca
  data:
    - secretKey: ca.crt
      remoteRef:
        key: kv/okd4/production/image-registry
        property: cacerts
