---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flux-system
  namespace: flux-system
spec:
  secretStoreRef:
    name: flux-system
    kind: SecretStore
  target: 
    name: flux-system
    # creationPolicy: Orphan
    # The operator creates the secret but does not set the ownerReference on the Secret.
    # That means the Secret will not be subject to garbage collection. If a secret with the same name already exists it will be updated.
    creationPolicy: Orphan
    template:
      metadata:
        annotations:
          ## kustomize.toolkit.fluxcd.io/reconcile: disabled (ignore secret from beeing reconciled by the kustommize controller)
          kustomize.toolkit.fluxcd.io/reconcile: disabled
      data:
        username: "${cluster_env}_flux_system_token_reader"
        password: "{{ .access_token }}"
  data:
  - secretKey: access_token 
    remoteRef:
      key: kv/okd4/production/flux
      property: gitlab_project_flux_system_token_reader
