apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: config-apps
  git:
    checkout:
      ref:
        branch: ${config_apps_git_branch}
    commit:
      author:
        email: fluxcdbot@lab.lab.okd.local
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: ${config_apps_git_branch}
  update:
    path: ${config_apps_root_path}
    strategy: Setters
