# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: apisix
#   name: capacitor
#   namespace: flux-system
# spec:
#   ingressClassName: apisix
#   rules:
#     - host: capacitor.example.com
#       http:
#         paths:
#           - backend:
#               service:
#                 name: capacitor
#                 port:
#                   number: 9000
#             path: /
#             pathType: Prefix
#   # tls: 
#   #   - hosts:
#   #       - capacitor.example.com
#   #     secretName: capacitor-tls
