apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: vault-secret-tomcat-metallb-chart
  namespace: tomcat-metallb
spec:
  keys:
    - flux_production_identity
    - flux_production_identity_pub
    - known_hosts
  path: kv/okd4/okd4-cli
  templates:
    identity: "{% .Secrets.flux_production_identity %}"
    identity.pub: "{% .Secrets.flux_production_identity_pub %}"
    known_hosts: "{% .Secrets.known_hosts %}"
  type: Opaque
