---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: apisix-control-plane-tls
  namespace: apisix
spec:
  secretStoreRef:
    name: okd4-apisix
    kind: SecretStore
  target:
    name: apisix-control-plane-tls
    template:
      type: tls
  data:
  - secretKey: tls.ca 
    remoteRef:
      key: kv/okd4/production/apisix
      property: pfsense-ca-bundle
  - secretKey: tls.crt 
    remoteRef:
      key: kv/okd4/production/apisix
      property: control-plane-tls-cert
  - secretKey: tls.key 
    remoteRef:
      key: kv/okd4/production/apisix
      property: control-plane-tls-key

