---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: apisix-credentials
  namespace: apisix
spec:
  secretStoreRef:
    name: okd4-apisix
    kind: SecretStore
  target:
    name: apisix-credentials
  data:
  - secretKey: admin 
    remoteRef:
      key: kv/okd4/production/apisix
      property: credentials.admin
  - secretKey: viewer 
    remoteRef:
      key: kv/okd4/production/apisix
      property: credentials.viewer
