---
apiVersion: v1
kind: Namespace
metadata:
  name: apisix
---
apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  name: ca-inject
  namespace: apisix