apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kumahq
  namespace: kuma-system
spec:
  interval: 24h
  type: oci
  url: oci://hub-registry.lab.okd.local/helm-charts/kumahq.github.io/charts