apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak
  namespace: keycloak
spec:
  commonName: keycloak
  dnsNames:
    - keycloak
  issuerRef:
    name: vault-issuer
    kind: Issuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  secretName: keycloak-tls