---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  secretStoreRef:
    name: okd4-keycloak
    kind: SecretStore
  target:
    name: keycloak-admin
  data:
  - secretKey: admin-password 
    remoteRef:
      key: kv/okd4/production/keycloak
      property: admin-password
