---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-spi
  namespace: keycloak
spec:
  secretStoreRef:
    name: okd4-keycloak
    kind: SecretStore
  target:
    name: keycloak-spi
  data:
  - secretKey: keycloak-spi.truststore.jks 
    remoteRef:
      key: kv/okd4/production/keycloak
      property: keycloak-spi.truststore.jks
      decodingStrategy: Base64
  - secretKey: spi-truststore-password
    remoteRef:
      key: kv/okd4/production/keycloak
      property: jks-password

#
# JKS
#

##
## cd ~/openshift-proxmox-terraform/okd-addons/certs/
##
## export PKI_JKS_PASSWORD=$(vault kv get -field jks-password kv/okd4/production/keycloak)
## export PKI_JKS_TRUSTSTORE_FILE=keycloak-spi.truststore.jks
##
##              keytool -importcert -noprompt -trustcacerts \
##                      -keystore $PKI_JKS_TRUSTSTORE_FILE \
##                      -storepass $PKI_JKS_PASSWORD \
##                      -alias pfsense-lab-okd-intermediate-ca \
##                      -file pfsense-lab-okd-intermediate-ca.crt
##
##              keytool -importcert -noprompt -trustcacerts \
##                      -keystore $PKI_JKS_TRUSTSTORE_FILE \
##                      -storepass $PKI_JKS_PASSWORD \
##                      -alias pfsense-lab-okd-root-ca \
##                      -file pfsense-lab-okd-root-ca.crt
##
## PKI_JKS_PASSWORD:
##  < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-64};echo;
##
##
## VAULT:
##
## keycloak-spi.truststore.jks:
## cat keycloak-spi.truststore.jks | base64 -w0 | vault kv patch kv/okd4/production/keycloak keycloak-spi.truststore.jks= -
## 
## spi-truststore-password (value from PKI_JKS_PASSWORD):
## < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-64};echo;