---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql
  namespace: keycloak
spec:
  secretStoreRef:
    name: okd4-keycloak
    kind: SecretStore
  target:
    name: postgresql-admin
  data:
  - secretKey: postgres-password
    remoteRef:
      key: kv/okd4/production/keycloak
      property: postgresql-admin-password
  - secretKey: password
    remoteRef:
      key: kv/okd4/production/keycloak
      property: postgresql-password
