apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: keycloak
spec:
  interval: 10m
  type: oci
  url: oci://hub-registry.lab.okd.local/helm-charts/charts.bitnami.com/bitnami
