---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: okd4-keycloak
  namespace: keycloak
spec:
  provider:
    vault:
      server: ${vault_address}
      path: ${vault_kv_engine_secret_mount_path}
      auth:
        kubernetes:
          mountPath: ${vault_auth_kubernetes_mount_path}
          role: keycloak
