---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: okd4-config-base
spec:
  provider:
    vault:
      server: ${vault_address}
      path: ${vault_kv_engine_secret_mount_path}
      auth:
        kubernetes:
          mountPath: ${vault_auth_kubernetes_mount_path}
          role: flux-system
