apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 24h
  type: oci
  url: oci://hub-registry.lab.okd.local/helm-charts/metallb.github.io
