apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: matheusfm 
  namespace: httpbin-mesh
spec:
  interval: 10m
  type: oci
  url: oci://registry.lab.okd.local/helm-charts/matheusfm.dev
