apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: secureapp-oidc
  namespace: httpbin
spec:
  plugins:
    - name: openid-connect
      enable: true
      config:
        discovery: https://keycloak.apps.lab.okd.local/realms/okd4/.well-known/openid-configuration
        scope: "openid profile"
        bearer_only: false
        realm: okd4
        redirect_uri: https://secureapp.apps.lab.okd.local/callback
        logout_path: /logout
      secretRef: secureapp-oidc-plugin-config