---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: myclient-oidc-plugin-config
  namespace: httpbin
spec:
  secretStoreRef:
    name: okd4-apisix
    kind: SecretStore
  target:
    name: openid-connect-plugin-config
    template:
      data:
        client_id: myclient
        client_secret: "{{ .client_secret }}"
  data:
  - secretKey: client_secret 
    remoteRef:
      key: kv/okd4/production/keycloak/openid-clients/apisix
      property: myclient.client_secret
