---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secureapp-oidc-plugin-config
  namespace: httpbin
spec:
  secretStoreRef:
    name: okd4-apisix
    kind: SecretStore
  target:
    name: secureapp-oidc-plugin-config
    template:
      data:
        client_id: secureapp
        client_secret: "{{ .client_secret }}"
  data:
  - secretKey: client_id
    remoteRef:
      key: kv/okd4/production/apisix
      property: secureapp-openid-connect-plugin-config-client-id
  - secretKey: client_secret 
    remoteRef:
      key: kv/okd4/production/keycloak/openid-clients/apisix
      property: secureapp.client_secret
