---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: server-admin-apisix-dev
  namespace: httpbin
spec:
  secretStoreRef:
    name: okd4-apisix
    kind: SecretStore
  target:
    name: server-admin-apisix-dev
  data:
  - secretKey: cert
    remoteRef:
      key: kv/okd4/production/apisix/apps/httpbin
      property: mtls_server_cert
  - secretKey: key 
    remoteRef:
      key: kv/okd4/production/apisix/apps/httpbin
      property: mtls_server_key
