apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: weave-gitops-oidc
  namespace: weaveworks
spec:
  plugins:
    - name: openid-connect
      enable: true
      config:
        discovery: https://keycloak.apps.lab.okd.local/realms/okd4/.well-known/openid-configuration
        scope: "openid profile"
        bearer_only: false
        realm: okd4
        redirect_uri: https://weave-gitops.apps.lab.okd.local/callback
      secretRef: weave-gitops-oidc-plugin-config