---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops-oidc-plugin-config
  namespace: weaveworks
spec:
  secretStoreRef:
    name: okd4-weave-gitops
    kind: SecretStore
  target:
    name: weave-gitops-oidc-plugin-config
    template:
      data:
        client_id: weave-gitops
        client_secret: "{{ .client_secret }}"
  data:
  - secretKey: client_secret 
    remoteRef:
      key: kv/okd4/production/keycloak/openid-clients/weave-gitops
      property: weave_gitops.client_secret
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: okd4-weave-gitops
  namespace: weaveworks
spec:
  provider:
    vault:
      server: ${vault_address}
      path: ${vault_kv_engine_secret_mount_path}
      auth:
        kubernetes:
          mountPath: ${vault_auth_kubernetes_mount_path}
          role: weave-gitops
