apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-transit
  namespace: hashicorp
spec:
  interval: 30m
  releaseName: vault-transit
  chart:
    spec:
      chart: vault
      version: "0.25.0"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: hashicorp
      interval: 12h
  driftDetection:
    mode: enabled
  upgrade:
    crds: CreateReplace
  values:
    global:
      tlsDisable: false
    injector:
      enabled: false
    server:
      affinity: ""
      ha:
        enabled: true
        replicas: 3
        raft: 
          enabled: true
          setNodeId: true
          config: |
            listener "tcp" {
              tls_disable = false
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              tls_client_ca_file  = "/vault/userconfig/vault-transit-tls/ca.crt"
              tls_cert_file = "/vault/userconfig/vault-transit-tls/tls.crt"
              tls_key_file  = "/vault/userconfig/vault-transit-tls/tls.key"
            }

            storage "raft" {
              path = "/vault/data"
            }

            service_registration "kubernetes" {}
      volumes:
        - name: tls
          secret:
            defaultMode: 420
            secretName: vault-transit-tls
      volumeMounts:
        - mountPath: /vault/userconfig/vault-transit-tls
          name: tls
