apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: hashicorp
spec:
  interval: 24h
  type: oci
  url: oci://hub-registry.lab.okd.local/helm-charts/helm.releases.hashicorp.com
