kind: Pod
apiVersion: v1
metadata:
  name: test-pod
  namespace: nfs-subdir-external-provisioner-system
spec:
  containers:
  - name: test-pod
    image: hub-registry.lab.okd.local/busybox:stable
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/SUCCESS && exit 0 || exit 1"
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: test-claim

