---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tomcat-metallb-repository
  namespace: tomcat-metallb-mesh
spec:
  provider:
    vault:
      server: ${vault_address}
      path: ${vault_kv_engine_secret_mount_path}
      auth:
        kubernetes:
          mountPath: ${vault_auth_kubernetes_mount_path}
          role: flux-system
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tomcat-metallb-repository
  namespace: tomcat-metallb-mesh
spec:
  secretStoreRef:
    name: tomcat-metallb-repository
    kind: SecretStore
  target:
    name: external-secret-tomcat-metallb-repository
    template:
      type: Opaque
      data:
        username: production_flux_helm_token_reader
        password: "{{ .access_token }}"
  data:
  - secretKey: access_token 
    remoteRef:
      key: kv/okd4/production/flux
      property: gitlab_group_helm_token_reader
