apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: policy-reporter-oidc
  namespace: kyverno
spec:
  plugins:
    - name: openid-connect
      enable: true
      config:
        discovery: https://keycloak.apps.lab.okd.local/realms/okd4/.well-known/openid-configuration
        scope: "openid profile"
        bearer_only: false
        realm: okd4
        redirect_uri: https://policy-reporter.apps.lab.okd.local/callback
      secretRef: policy-reporter-oidc-plugin-config