---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: policy-reporter-oidc-plugin-config
  namespace: kyverno
spec:
  secretStoreRef:
    name: okd4-kyverno
    kind: SecretStore
  target:
    name: policy-reporter-oidc-plugin-config
    template:
      data:
        client_id: kyverno-policy-reporter
        client_secret: "{{ .client_secret }}"
  data:
  - secretKey: client_secret 
    remoteRef:
      key: kv/okd4/production/keycloak/openid-clients/kyverno
      property: policy-reporter.client_secret
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: okd4-kyverno
  namespace: kyverno
spec:
  provider:
    vault:
      server: ${vault_address}
      path: ${vault_kv_engine_secret_mount_path}
      auth:
        kubernetes:
          mountPath: ${vault_auth_kubernetes_mount_path}
          role: kyverno
