---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jks-secret
  namespace: confluent
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: confluent-control-center
  target:
    name: jks-secret
  data:
  - secretKey: password-key
    remoteRef:
      key: jksPassword
      property: jksPassword
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: confluent-control-center
  namespace: confluent
spec:
  provider:
    vault:
      server: ${vault_address}
      path: kv/confluent
      auth:
        kubernetes:
          mountPath: ${vault_auth_kubernetes_mount_path}
          role: confluent-control-center
