apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/confluent-control-center
  - imagepolicy.yaml
  - ingress.yaml
  - release.yaml
  - repository.yaml
  - certificate-control-center.yaml
  - certificate-example-com.yaml
  - externalsecret-jks-secret.yaml
  - clusterpolicy-add-mnt-volume-keystores-control-center-confluent.yaml
  - confluent-ca-bundle.yaml