---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gitops-tekton-welcome-pipeline
  namespace: welcome-app-dev
spec:
  provider:
    vault:
      server: ${vault_address}
      path: kv/gitops/tekton-welcome-pipeline
      auth:
        kubernetes:
          mountPath: ${vault_auth_kubernetes_mount_path}
          role: external-secrets-gitops
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-webhook
  namespace: welcome-app-dev
spec:
  secretStoreRef:
    name: gitops-tekton-welcome-pipeline
    kind: SecretStore
  target:
    name: external-secret-gitlab-webhook
  data:
  - secretKey: token 
    remoteRef:
      key: kv/gitops/tekton-welcome-pipeline/gitlab-webhook
      property: secretToken
