---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pfsense-okd-intermediate-ca-key-pair
  namespace: cert-manager
spec:
  secretStoreRef:
    name: okd4
    kind: SecretStore
  target:
    name: pfsense-okd-intermediate-ca-key-pair
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .certificate }}"
        tls.key: "{{ .private_key }}"
  data:
  - secretKey: certificate
    remoteRef:
      key: pfsense-ca
      property: intermediate
  - secretKey: private_key
    remoteRef:
      key: pfsense-ca
      property: intermediate_private_key
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: okd4
  namespace: cert-manager
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: ${vault_auth_kubernetes_mount_path}
          role: external-secrets-okd4
      path: ${vault_kv_engine_secret_mount_path}
      server: ${vault_address}
