apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 24h
  type: oci
  url: oci://hub-registry.lab.okd.local/helm-charts/charts.external-secrets.io
