apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 24h
  type: oci
  url:  oci://hub-registry.lab.okd.local/helm-charts/kubernetes-sigs.github.io/metrics-server
