# kind: Route
# apiVersion: route.openshift.io/v1
# metadata:
#   name: admin-apisix-dev
#   namespace: ingress-apisix
# spec:
#   host: admin.apisix.dev
#   to:
#     kind: Service
#     name: apisix-gateway
#     weight: 100
#   port:
#     targetPort: apisix-gateway-tls
#   tls:
#     termination: passthrough      
#   wildcardPolicy: None
