apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mtls-root-certificate
  namespace: kuma-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: kuma-mtls-root-ca
  target:
    name: mtls-root-certificate
    template:
      metadata:
        labels:
          kuma.io/mesh: default
      type: system.kuma.io/secret
      data:
        value: "{{ .certificate }}"    
  data:
  - secretKey: certificate
    remoteRef:
      key: kuma-mtls-root-ca
      property: tls.crt