---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kuma-mtls-root-ca
  namespace: kuma-system
spec:
  provider:
    kubernetes:
      remoteNamespace: kuma-system
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        token:
          bearerToken:
            name: eso-store-token
            key: token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-store-sa
  namespace: kuma-system
---
apiVersion: v1
kind: Secret
metadata:
  name: eso-store-token
  namespace: kuma-system
  annotations:
    kubernetes.io/service-account.name: eso-store-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kuma-system
  name: eso-store-role
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-store-rb
  namespace: kuma-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-store-role
subjects:
- kind: ServiceAccount
  name: eso-store-sa
  namespace: kuma-system
