apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: kuma-oidc
  namespace: kuma-system
spec:
  plugins:
    - name: openid-connect
      enable: true
      config:
        discovery: https://keycloak.apps.lab.okd.local/realms/okd4/.well-known/openid-configuration
        scope: "openid profile"
        bearer_only: false
        realm: okd4
        redirect_uri: https://kuma-control-plane.apps.lab.okd.local/callback
      secretRef: kuma-oidc-plugin-config