---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kuma-oidc-plugin-config
  namespace: kuma-system
spec:
  secretStoreRef:
    name: okd4-kuma
    kind: SecretStore
  target:
    name: kuma-oidc-plugin-config
    template:
      data:
        client_id: kuma
        client_secret: "{{ .client_secret }}"
  data:
  - secretKey: client_secret 
    remoteRef:
      key: kv/okd4/production/keycloak/openid-clients/kuma
      property: kuma.client_secret
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: okd4-kuma
  namespace: kuma-system
spec:
  provider:
    vault:
      server: ${vault_address}
      path: ${vault_kv_engine_secret_mount_path}
      auth:
        kubernetes:
          mountPath: ${vault_auth_kubernetes_mount_path}
          role: kuma
