apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus3-image-registry
  namespace: welcome-app-pipeline
spec:
  secretStoreRef:
    name: gitops-tekton-welcome-pipeline
    kind: SecretStore
  target:
    name: external-secret-nexus3-image-registry
    template:
      type: kubernetes.io/basic-auth
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: "1"
          tekton.dev/docker-0: https://registry.lab.okd.local
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
  - secretKey: username
    remoteRef:
      key: kv/gitops/tekton-welcome-pipeline/nexus3-image-registry
      property: username
  - secretKey: password
    remoteRef:
      key: kv/gitops/tekton-welcome-pipeline/nexus3-image-registry
      property: password
