---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-pr-image-updater
  namespace: welcome-app-pipeline
spec:
  secretStoreRef:
    name: gitops-tekton-welcome-pipeline
    kind: SecretStore
  target:
    name: external-secret-gitlab-pr-image-updater
    template:
      type: Opaque
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: "1"
      data:
        token: "{{ .token }}"
  data:
  - secretKey: token 
    remoteRef:
      key: kv/gitops/tekton-welcome-pipeline/gitlab-pr-image-updater
      property: token
