kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:openshift:scc:nonroot-v2
  namespace: welcome-app-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: welcome-app-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:nonroot-v2
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:openshift:scc:hostnetwork-v2
  namespace: welcome-app-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: welcome-app-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:hostnetwork-v2
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:openshift:scc:anyuid
  namespace: welcome-app-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: welcome-app-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:openshift:scc:restricted
  namespace: welcome-app-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: welcome-app-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:restricted
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:openshift:scc:hostmount-anyuid
  namespace: welcome-app-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: welcome-app-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:hostmount-anyuid
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:openshift:scc:machine-api-termination-handler
  namespace: welcome-app-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: welcome-app-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:machine-api-termination-handler
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:openshift:scc:hostnetwork
  namespace: welcome-app-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: welcome-app-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:hostnetwork
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:openshift:scc:hostaccess
  namespace: welcome-app-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: welcome-app-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:hostaccess
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:openshift:scc:node-exporter
  namespace: welcome-app-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: welcome-app-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:node-exporter
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:openshift:scc:privileged
  namespace: welcome-app-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: welcome-app-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
